# DBT Project Configuration
# This file defines the project structure and model configurations

name: 'lending_club_pipeline'
version: '1.0.0'
config-version: 2

# Project profile (must match profile name in profiles.yml)
profile: 'lending_club_pipeline'

# Directories
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Build artifacts
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

# Model configurations
models:
  lending_club_pipeline:
    # Source layer: Raw data ingestion without transformation
    # Materialized as tables for raw data persistence
    source:
      +materialized: table
      +schema: source
      +contract:
        enforced: true
    
    # Staging layer: Light transformations, one model per source
    # Materialized as tables to ensure quarantine filtering happens before downstream access
    # Changed from view to table to enforce dependency order with quarantine tables
    staging:
      +materialized: table
      +schema: staging
      +contract:
        enforced: true
      
      # Quarantine models must be tables and built before other staging models
      quarantine_stg_customer:
        +materialized: table
        +tags: ['quarantine', 'data_quality']
      
      quarantine_stg_account:
        +materialized: table
        +tags: ['quarantine', 'data_quality']
      
    # Intermediate layer: Business logic, joins, filters
    # Materialized as incremental tables with merge strategy for CDC processing
    intermediate:
      +materialized: incremental
      +schema: intermediate
      +incremental_strategy: merge
      +on_schema_change: fail
      +contract:
        enforced: true
      
    # Marts layer: Final business-ready outputs
    # Materialized as incremental tables for performance and CDC support
    marts:
      +materialized: incremental
      +schema: marts
      +incremental_strategy: merge
      +on_schema_change: fail
      +contract:
        enforced: true

# Seeds configuration
seeds:
  lending_club_pipeline:
    +schema: seeds

# Snapshots configuration
# Snapshots implement SCD2 (Slowly Changing Dimension Type 2) tracking
# to maintain historical versions of records with validity timestamps
snapshots:
  lending_club_pipeline:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: loaded_at
    +invalidate_hard_deletes: true
    +contract:
      enforced: true
    # Snapshot-specific configurations
    +unique_key: id
    # Check strategy can be overridden per snapshot model
    # Options: timestamp (default), check (compare all columns)
    # For models without updated_at column, use check_cols: all

# Documentation
docs-paths: ["docs"]

# Quoting configuration
quoting:
  database: false
  schema: false
  identifier: false
